name: Build-GM-PRO-ULTIMATE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP8266 Core SDK 2.0.0
        run: |
          arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266@2.0.0 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Install Required Libraries
        run: |
          arduino-cli lib install "ESP8266 and ESP32 OLED driver for SSD1306 displays"

      - name: Compile and Merge Firmware
        run: |
          mkdir -p build
          # 1. Compile file INO
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --output-dir ./build GM-PRO-ULTIMATE.ino
          
          # 2. Bikin file kosong untuk SPIFFS (Cara paling aman jika tool mklittlefs versi 2.0.0 sulit dipanggil)
          dd if=/dev/zero of=./build/spiffs.bin bs=1k count=1024
          
          # 3. Gabungkan Firmware (Karena SDK 2.0.0 sangat tua, kita fokus ambil file .bin utamanya dulu)
          cp ./build/GM-PRO-ULTIMATE.ino.bin ./build/FULL_FIRMWARE.bin

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: GM-PRO-V39-BIN
          path: ./build/FULL_FIRMWARE.bin
